### ISSUE TITLE
Shutdown Timer funktioniert nicht, während Titel spielt

### ISSUE THREAD

**Issue by dpuschek** [seisfeld/TonUINO#10]
Box spielt die ganze Nacht durch.

**Comment by seisfeld** [comment]
Das ist Absicht. Der shutdown timer ist kein sleep timer und zählt nur runter wenn nichts gespielt wird. Das soll den Akku schützen wenn man vergisst den TonUINO auszuschalten. Momentan ist in meiner Version kein sleep timer geplant. In Thorstens DEV Version ist diese Funktion allerdings enthalten. Vielleicht probierst du die mal aus.

**Comment by dpuschek** [comment]
Schade, dann habe ich es falsch verstanden. Sollte vielleicht deutlicher in der Anleitung erwähnt werden, dass der shutdown timer nur bei Inaktivität läuft.
In Deinem tonuino.ino code finde ich 5x die Zeile: "shutdownTimer(STOP);"
Wenn ich die einfach alle entferne, könnte es doch funktionieren?
Thorstens DEV unterstützt meines Wissens die CubieKid-Platine nicht (Flipflop zurücksetzen, bzw. im Betrieb nicht zurücksetzen)?

Schöne Ostertage,
Dominik

**Comment by seisfeld** [comment]
> In Deinem tonuino.ino code finde ich 5x die Zeile: "shutdownTimer(STOP);"
> Wenn ich die einfach alle entferne, könnte es doch funktionieren?

Naja, dann klappt dir die Box auch aus heiterem Himmel beim anlernen von Karten oder im Elternmenü weg. Das müsste man sich genauer ansehen. Du könntest z.B. L621 in `shutdownTimer(START);` ändern. Dann startet eine aufgelegte Karte den Timer. Macht man dann nichts weiter geht die Box nach der eingestellten Zeit aus. Es gibt halt keine UI um das vernünftig zu administrieren.

> Thorstens DEV unterstützt meines Wissens die CubieKid-Platine nicht (Flipflop zurücksetzen, bzw. im Betrieb nicht zurücksetzen)?

Du musst nur die shutdownPin Logik invertieren (LOW für aus und HIGH für an). Und den Teil in Setup ganz nach oben verschieben.

Aber das führt jetzt hier zu weit...

**Comment by dpuschek** [comment]
Danke für die Tipps. Ich werde bei Deiner Version bleiben. Nur noch eine letzte Frage dazu (oder ich probiere es einfach aus): Setzt ein erneutes Aufrufen der Funktion "shutdownTimer(START);" einen schon laufenden Timer auf 0 zurück oder läuft ein laufender Timer weiter? So wie ich das sehe, müsste zumindest ein STOP direkt gefolgt von START ihn auf jedenfall zurücksetzen?

**Comment by seisfeld** [comment]
START setzt den Timer zurück. Ein vorheriges STOP ist nicht nötig:

https://github.com/seisfeld/TonUINO/blob/0fe079ed343c6fbb7db9d9295993d8d013b3209a/tonuino.ino#L1366-L1373
