### ISSUE TITLE
Poweroff für Pololu

### ISSUE THREAD

**Issue by qutschwalze** [seisfeld/TonUINO#11]
Hi, 
ich nutze deine angepasste Version für meine Box. Funktioniert super, allerdings hatte ich gestern meinen Pololu Switch bekommen. Sobald ich diesen anschließe und dann einschalte ist für ca. 2 Sekunden die Box aktiv und danach sofort wieder aus. 
Ich habe festgestellt, dass du den Pin7 gleich nach dem Start auf High setzt und dadurch mein Schalter sofort alles wieder abschaltet. Passe ich das im Quellcode an, funktioniert alles einwandfrei. 
Habe ich irgendwas übersehen? Das Problem müsste doch jeder haben, der den Switch mit Pin7 und Pololu-Off verbindet.

**Comment by seisfeld** [comment]
Die Abschaltlogik ist für die CubieKid Schaltung und nicht für den Pololu Switch. Diese ist (aus Gründen) genau invertiert. Wenn du die Logik umdrehst (Zeilen s.u.) kannst du sie aber 1:1 für den Pololu Switch verwenden.

https://github.com/seisfeld/TonUINO/blob/35dd214eba0e2916c17df8fe9f88e42c9ca6c50c/tonuino.ino#L457

https://github.com/seisfeld/TonUINO/blob/35dd214eba0e2916c17df8fe9f88e42c9ca6c50c/tonuino.ino#L598

Der Grund warum das nicht "jeder" hat, ist wohl der, daß der Fork maximal im niedrigen einstelligen Prozentbereich der Userbase eingesetzt wird. ;) Dazu kommt, nicht jeder nutzt auch den Pololu Switch.

**Comment by qutschwalze** [comment]
Macht Sinn, ich hatte die Befürchtung ich hätte was falsch angeschlossen.

**Comment by seisfeld** [comment]
Ich habe in 63f696d ein #define dafür eingebaut. Der shutdown pin Logik lässt sich nun einfach umschalten.
