### ISSUE TITLE
Wiedergabe stoppen, wenn Karte weg

### ISSUE THREAD

**Issue by maxxe88** [seisfeld/TonUINO#19]
Hi, gibt es eine Möglichkeit die Wiedergabe zu stoppen, wenn man die Karte entfernt?

Liebe Grüße Max

**Comment by seisfeld** [comment]
Nein. In meiner Firmware ist dies momentan nicht geplant. Es gibt aber durchaus andere Firmwares für den TonUINO, die das umgesetzt haben. Schaue am besten mal im [Community Forum](https://discourse.voss.earth), vorbei.

**Comment by maxxe88** [comment]
Ok, schade. Trotzdem vielen dank
