### ISSUE TITLE
MP3 files für non-mac-os user

### ISSUE THREAD

**Issue by uwjhn** [seisfeld/TonUINO#2]
Wäre es möglich die "Kommando" MP3's für die SD karte hochzuladen? Ich habe leider gerade keinen Zugriff auf einen Mac.... Falls dich die Größe stört, könntest du auch ggf. einfach einen extra Branch dafür erstellen.

**Comment by seisfeld** [comment]
Das würde ich eigentlich nur ungern machen. An den Prompts ändert sich auch ggf. öfters mal was und ich möchte eigentlich jedem die Möglichkeit geben die Stimme der Box so zu gestalten wir er/sie möchte. Auch um ggf. die Länge der Prompts anzupassen. Außerdem weiss ich nich wie Apple das mit den Rechten hält.

Davon ab, es gibt aber auch für Linux diverse tools die ähnliches machen. Einige Beispiele finden sich hier: https://askubuntu.com/questions/501910/how-to-text-to-speech-output-using-command-line

Für Windows, weiss ich leider nicht. Zur Not kann man sich ja immer noch in ein Mikro schnappen und die paar Sätze eben selbst einsprechen (haben mir auch schon User von berichtet).

**Comment by seisfeld** [comment]
Achja, danke daß Du meine alternative Firmware einsetzen möchtest. Dafür macht man sich die ganze Arbeit ja. :) 👍

**Comment by uwjhn** [comment]
ok. ich gucke mir die linux alternative an. meine erfahung ist, dass die eher so mager ist :)
ansonsten muss ich mein uralt-macbook mal wieder anwerfen.
