### ISSUE TITLE
IRRemote decode(&results) function deprecated

### ISSUE THREAD

**Issue by zafzafzaf** [seisfeld/TonUINO#24]
Hi, 
thanks for great work! 
After repeated unsuccessfull ir teach tries, I saw the following error messages in Serial Monitor.
"The function decode(&results)) is deprecated and may not work as expected! Just use decode() - without any parameter.", tried to change just what it says, sure it was not enough and I saw all buttons recognized as 0x000...
After googling (ie. https://forum.arduino.cc/index.php?topic=724388.0) , found out that irremote codes needs to be updated to be able to use with the new version. 
https://github.com/Arduino-IRremote/Arduino-IRremote
I would love to update the code for the newest version and make pull request(I am new to github), but for a faster result was just downgrading the irremote Library to 2.7 was much easier, and works great. Although the documentation refers for 3.x, same error occurs on 2.8.1 as well. 
Maybe you can add on the documentation that (for the time being) not the newest version but 2.7 of the library should be installed...
Thanks! 
Cheers!
Zaf

**Comment by seisfeld** [comment]
Yeah I did got this reported a couple times now. I updated the sketch to support the latest Arduino-IRremote version. Please test and report any issues. Thanks.

**Comment by zafzafzaf** [comment]
Thank you for rapid update. Works as aspected with the newest library now...

**Comment by seisfeld** [comment]
Awesome. Thanks for checking.
