### ISSUE TITLE
Wechsel von +/- und previous/next im 3-Button-Layout

### ISSUE THREAD

**Issue by bkk87** [seisfeld/TonUINO#25]
Hi Stephan, ich habe eine "Box ohne Bohren" und bin damit leider auf ein 3-Button-Layout beschränkt.

Da meine MP3s normalisiert sind, wird die Lautstärke nur selten verändert. 
Häufiger wird vorheriger/nächster Track genutzt.

Wie denkst du über eine zusätzliche Konfigurationsmöglichkeit (per Variable) in deiner Firmware, um vorheriger/nächster Track mit einem kurzen Button-Press und dafür die Lautstärke mit einem langen zu verändern?

**Comment by seisfeld** [comment]
Damit kam mein kleiner Neffe überhaupt nicht klar, deswegen ist es bei mir explizit so rum. Ich finde es auch deutlich weniger schlimm wenn man aus versehen einen tick lauter macht, als wenn man aus versehen ständig den Track wechselt. Doppelte Belegung ist halt bei kleinen Kindern so eine Sache. Zudem bin ich über die Zeit ein absoluter Fan von 5 Tasten geworden (anfangs war das nicht so...). Daher denke ich nicht, daß ich das in meiner Firmware ändern werde.
