### ISSUE TITLE
DFPlayer

### ISSUE THREAD

**Issue by stefanbierl** [seisfeld/TonUINO#3]
Hi Stephan,

vorweg ein ganz großes Dankeschön für deinen Fork!
Habe mein Projekt eigentlich fertig umgesetzt, musste hierzu lediglich den DFPlayer von SoftwareSerial auf HardwareSerial umstellen (nutze ein Mega 2560 Board).
Damit funktionierte dann die Kommunikation zum DFPlayer

//SoftwareSerial secondarySerial(softwareSerialRxPin, softwareSerialTxPin);    
//DFMiniMp3<SoftwareSerial, Mp3Notify> mp3(secondarySerial);
DFMiniMp3<HardwareSerial, Mp3Notify> mp3(Serial1);

Es hat alles wunderbar funktioniert, bis ich vorgestern die SD-Karte mit neuen Hörbüchern befüllt habe. Seitdem bekomme ich einen error code 1 bzw. 255.
Ich finde den Fehler nicht, da ich aber sonst nichts geändert habe, muss es ja fast an den Daten liegen?!

SD-Card ist wie beschrieben, via Terminal unter MacOS von sämtlichen versteckten Dateien befreit worden. Habe letztendlich zum debugging nur noch einen Ordner rüber kopiert, um weitere Dateinahmen-Fehler auszuschließen...

Kannst Du mir bezüglich der Error-Codes weiterhelfen. Habe diesbezüglich leider nichts gefunden.

Hier das Log:
䱊=x|⸮Hz⸮Ssys | TonUINO JUKEBOX
sys | by Thorsten Voß
sys | Stephan Eisfeld
---------------------
sys | initializing nfc module
sys | initializing mp3 module
sys |    volume: 15
sys |    tracks: mp3 | error code 1
mp3 | error code 1
mp3 | error code 255
65516
sys | initializing rng
sys | initializing buttons
sys | system is ready
mp3 | error code 1
mp3 | sd card removed 
mp3 | sd card inserted 
nfc | tag detected
nfc | successfully read tag
nfc | tag is one of ours
nfc |   folder: 1
nfc |     mode: story mode
sys | starting playback
mp3 | error code 1
mp3 | error code 255
mp3 | story mode > randomly play one of 0 tracks in folder 1
mp3 | story mode > folder 1 > track 1/0
mp3 | error code 1

Würde mich sehr freuen wenn Du mir helfen kannst.

Vielen Dank und schöne Grüße
Stef

**Comment by seisfeld** [comment]
Hallo Stef,

erstmal danke dass du meinen Fork probierst. :-)

Die Bedeutung der codes findest Du am Anfang von [DFMiniMp3.h](https://github.com/Makuna/DFMiniMp3/blob/master/src/DFMiniMp3.h) im Repo der eingesetzten Library. Ich habe mich eben mal hingesetzt und mit a3d3e06 gibt die Firmware jetzt nicht mehr die Nummern sondern die Bedeutung aus. Wenn du also deinen Clone updatest, siehst du das bei dir auch. Allerdings sei gesagt das `1` für _busy_ und `255` für _general_ steht - hilft dir also nicht wirklich weiter.

Wenn der Sketch vorher funktioniert hat und du wirklich nur die SD Karte verändert hast, sehe ich das so wie du. Wahrscheinlich kommt der DfPlayer mit der Karte nicht klar. Leider ist der DfPlayer wirklich sehr picky was die Karte angeht. Es reicht schon die Karte 1x aus dem PC/Mac rauszunehmen ohne vorher sauber ungemounted zu haben und schon spinnt der DfPlayer rum. Das hatte ich auch schon öfter. Das einzige was in so einem Fall hilft ist die Karte zu formatieren und komplett neu zu bespielen (es hilft also wenn man immer ne 1:1 Kopie der Karte auf dem Rechnet hat). Das könntest Du mal probieren. Ansonsten wüsste ich nicht wo das Problem sein soll - unter der Prämisse das es vorher geklappt hat und die Benamsung der Dateien korrekt ist usw.

Gruß
Stephan

**Comment by stefanbierl** [comment]
Hi Stephan,

vielen Dank für Deine Hilfe. Ich bin weiter auf der Suche nach dem Fehler. Hatte letze Nacht noch die DF-Examples ausprobiert und auch ein anderes Arduino Board.
Auch die SD-Card sowohl mit MacOS als auch mit Windows formatiert und neu beschrieben...
Was mir noch fehlt zum testen ist eine zweite SD-Card. Evtl. is auch das Modul hinüber. 
Sollte ich was rausfinden, meld ich mich 😉
Und sollte dann endlich mal alles laufen, geht's vielleicht auch an ein paar extra's, die ich dann natürlich auch gerne bereitstelle.

Danke und Grüße
Stef

**Comment by seisfeld** [comment]
Hi Stef,

ich hab mir beim einbauen in den Lautsprecher auch schon einen DfPlayer zerstört. Da war irgendwo einen Lötbrücke auf der Platine, vermutlich auf den Ausgängen. Danach tat sich gar nichts mehr. Ich weiss allerdings nicht mehr welcher Fehler dann da kam. Ich hab seitdem immer einen kleinen eisernen Vorrat an Hardware da. ;-) Auch beliebt, RX/TX verdreht. Aber da hast du ja sicher ausgeschlossen richtig?

Gruß
Stephan

**Comment by stefanbierl** [comment]
neue SD neues Glück... geht alles! 
Jetzt ist meine Vermutung dass die andere SD vielleicht ma zu nahe an den Magneten des Lautsprechers gekommen ist. Wobei es dann schon wundert, das die Karte am Mac / Windows einwandfrei funzt. Egal! 😉

**Comment by seisfeld** [comment]
Das ist wirklich komisch, aber Hauptsache es geht nun alles wie gewünscht! Viel Spass mit der Box.
