### ISSUE TITLE
Upgrade to new Makuna/DFMiniMp3 API?

### ISSUE THREAD

**Issue by AlmightyFrog** [seisfeld/TonUINO#30]
I just wanted to ask, what you think the future is for this Fork. With the new DFPlayer there are massive problems which makes them either not work or very inconvenient.

It seems like at least for MH2024K-16SS with no checksum mode and different opcodes operation is improved.
E.g. look at https://github.com/Makuna/DFMiniMp3/commit/d603f8e4f6d4cba7ad41d6c526f4cc7322940c96 which seems like best use latest git instead of a release.

Anyhow: Are you planning to upgrade API to new version? Otherwise, if I would find time to (could be between days and months) to try to make a PR for it, would you merge even if it is not totally shiny?

**Comment by seisfeld** [comment]
Currently I don't have the time to work on this Fork. Also it suits my requirements. As for the DFPlayer, Leiterkartenpiraten have their own player now which fixes the issues which other players have. If you live in Germany (or in some of the other few selected countries) you can order it [here](https://www.leiterkartenpiraten.de/produkt/lkp-player/).

**Comment by AlmightyFrog** [comment]
Thanks for the hint with the LKP-Player. That would be easiest solution.
Maybe i'm gonna buy there some, but as i still have DFPlayer modules on my hand it would sad to not use them.

I didn't have a deep look at it but it can't be that hard i guess adapting the API and maybe altering some small locations; I'll have a look...
